name: Build and Release Electron App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Build Electron Windows App
      run: npm run build:win

    - name: Create Release and Upload Asset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v1.0.1 --title "Execute Pro 1.0.1" --notes "Fix transparent widget rendering." || true
        gh release upload v1.0.1 release2/*.exe --clobber
