name: Build and Release Electron App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Build and Publish Electron App
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build:win -- -c.publish.provider=github -c.publish.releaseType=release --publish always
